name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - main
    workflow_dispatch:

permissions: write-all

#  並列実行阻止
concurrency:
  group: ${{ github.workflow }}

env:
  DOCKER_REPOSITORY: haruapp
  DOCKER_IMAGE_NAME: myenglish-server
  RELEASE_BRANCH: main

jobs:
  release:
    # マージされたときのみ実行
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # DockerHubにログイン : https://github.com/docker/login-action
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Build Docker image'
        run: docker build --platform linux/arm64 -t ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest ./MyEnglishServer/
      - name: 'Push Docker Image'
        run: docker push ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest

