spring:
  application:
    name: MyEnglishServer
  datasource:
    url: ${MYENGLISH_DB_DSN}
    username: root
    password: Password1
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${G_AUTH_CLIENT_ID}
            client-secret: ${G_AUTH_SECRET}
  main:
    allow-bean-definition-overriding: true
  # session
  # Redis
  data:
    redis:
      host: ${MYENGLISH_REDIS_DSN}
      #spring.data.redis.host=127.0.0.1
      port: 6800
      password: null
# Driver
# Database Connection URL
#spring.datasource.url=jdbc:mysql://localhost:3306/myenglishdb
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# Log
logging:
  level:
    myenglish: DEBUG

jwt:
  secret-key: ${JWT_SECRET_KEY}
front:
  path: ${FRONT_PATH}
#server.servlet.session.timeout=3600
#spring.session.redis.flush-mode=on_save
#spring.session.redis.namespace=spring:session
